Repository hackathon-equipe/EquipeHackaton, pull requests merged in 2024-07, with the labels that each got.

#2 Remover arquivos desnecessários
  src/App.vue
  src/assets/main.css
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/views/AboutView.vue
  src/views/HomeView.vue
Labels: CHORE

#5 feat-4: criado a base de home page
  src/App.vue
  src/assets/main.css
  src/router/index.js
  src/views/homeView.vue
Labels: FEAT

#7 Feat 6: Componentizando a página inicial
  src/assets/main.css
  src/components/help/ButtonHelp.vue
  src/components/help/HelpArea.vue
  src/components/navbar/DefaultNavbar.vue
  src/components/navbar/LinksNavbar.vue
  src/components/terminal/DefaultTerminal.vue
  src/views/homeView.vue
Labels: FEAT, STYLE

#8 Criar json com as infromações de cada membro
  src/assets/membros.json
Labels: CHORE

#19 STYLE: alterado gap entre os links da navbar
  src/components/navbar/DefaultNavbar.vue
Labels: STYLE

#20 Criar json com as informações de cada projeto
  src/assets/projetos.json
Labels: CHORE

#21 STYLE: criado animação do help #16
  src/components/help/HelpArea.vue
Labels: STYLE

#23 STYLE: help ficou igual o figma #15
  src/components/help/HelpArea.vue
Labels: STYLE

#24 Add props no component do terminal
  src/components/terminal/DefaultTerminal.vue
  src/views/homeView.vue
Labels: FEAT

#25 FEAT: Adding routers
  src/components/navbar/DefaultNavbar.vue
  src/router/index.js
  src/views/aboutView.vue
  src/views/developersView.vue
  src/views/homeView.vue
  src/views/projectView.vue
Labels: FEAT

#26 Criar pagina da equipe
  src/components/terminal/DefaultTerminal.vue
  src/views/developersView.vue
Labels: FEAT

#29 Fix: Padronizar rotas
  src/components/navbar/DefaultNavbar.vue
  src/views/developersView.vue
  src/views/homeView.vue
Labels: FIX

#30 style: alterado tempo de animacao do help, corrigido animacao de carregamento no terminal
  src/components/help/HelpArea.vue
  src/components/terminal/DefaultTerminal.vue
  src/router/index.js
  src/views/homeView.vue
Labels: STYLE

#32 Feat: Criado Pagina de Projetos e Criado as rotas
  src/assets/projetos.json
  src/components/terminal/DefaultTerminal.vue
  src/router/index.js
  src/views/projectView.vue
  src/views/projectsViews/projectArthistoView.vue
  src/views/projectsViews/projectFabricaClassView.vue
  src/views/projectsViews/projectFabricaNodeView.vue
  src/views/projectsViews/projectPoeiraoView.vue
  src/views/projectsViews/projectTPInterativaView.vue
Labels: FEAT

#33 feat: criado pagina de cada projeto #18
  src/components/terminal/DefaultTerminal.vue
  src/views/projectsViews/projectArthistoView.vue
  src/views/projectsViews/projectFabricaClassView.vue
  src/views/projectsViews/projectFabricaNodeView.vue
  src/views/projectsViews/projectPoeiraoView.vue
  src/views/projectsViews/projectTPInterativaView.vue
Labels: FEAT

#39 Fix help area
  src/components/help/HelpArea.vue
  src/views/aboutView.vue
  src/views/developersView.vue
  src/views/homeView.vue
  src/views/projectView.vue
Labels: FIX

#40 FEAT: Criando texto do sobre
  src/components/terminal/DefaultTerminal.vue
  src/views/aboutView.vue
Labels: FEAT

#42 FIX: Arrumando informações dos membros
  src/components/terminal/DefaultTerminal.vue
  src/views/aboutView.vue
Labels: FIX
